# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerennityLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=250, verbose_name='Cliente')),
                ('mac_address', models.CharField(max_length=250, verbose_name='MacAddress')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SN')),
                ('installed', models.DateField(blank=True, null=True, verbose_name='Instalado')),
                ('valid', models.DateField(blank=True, null=True, verbose_name='Valido')),
                ('key', models.TextField(blank=True, null=True, verbose_name='Chave')),
                ('active', models.NullBooleanField(default=True, verbose_name='Licença Ativa')),
                ('tipo_license', models.PositiveIntegerField(choices=[(0, 'Amostra'), (1, 'Demonstração'), (2, 'Licenciado')], default=0, verbose_name='Status')),
                ('nao_enviar_aviso', models.NullBooleanField(default=False)),
                ('data_ultimo_aviso', models.DateTimeField(blank=True, null=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid'],
            },
        ),
    ]
