# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechUser',
            fields=[
                ('username', models.CharField(db_column='NOME_USER', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(blank=True, db_column='SENHA_USER', max_length=10, null=True)),
                ('ip', models.CharField(blank=True, db_column='IP_HOST', max_length=13, null=True)),
                ('nickname', models.CharField(blank=True, db_column='APELIDO_USER', max_length=20, null=True)),
                ('skype', models.CharField(blank=True, db_column='APELIDO_SKYPE', max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'TECHCD].[DBO].[USUARIOS',
            },
        ),
        migrations.CreateModel(
            name='TechDjangoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_user', models.CharField(max_length=40)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
