# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20161207_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigIntegerField(db_column='COD_CLI', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NOME_CLI', max_length=80, null=True)),
            ],
            options={
                'db_table': 'TECHCD].[DBO].[CLIENTES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuarios',
            fields=[
                ('cod_grupo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc_grupo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'TECHCD].[DBO].[GRUPO_USUARIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerennityLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=250, verbose_name='Cliente')),
                ('mac_address', models.CharField(max_length=250, verbose_name='MacAddress')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='SN')),
                ('installed', models.DateField(blank=True, null=True, verbose_name='Instalado')),
                ('valid', models.DateField(blank=True, null=True, verbose_name='Valido')),
                ('key', models.TextField(blank=True, null=True, verbose_name='Chave')),
                ('tecnico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid'],
            },
        ),
        migrations.RemoveField(
            model_name='techdjangouser',
            name='django_user',
        ),
        migrations.DeleteModel(
            name='TechDjangoUser',
        ),
    ]
