# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161222_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perennitylicense',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='perennitylicense',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
