# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170112_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perennitylicense',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SN'),
        ),
    ]
