# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20170112_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.IntegerField(choices=[(1, 'SUGESTÃO'), (2, 'RECLAMÇÃO'), (3, 'RECLAMAÇÃO'), (4, 'RECLAMAÇÃO ANONIMA')], default=1)),
                ('assunto', models.CharField(max_length=100)),
                ('menssagem', models.TextField()),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_created'],
                'verbose_name': 'Contato',
            },
        ),
    ]
