# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='perennitylicense',
            name='tipo_license',
            field=models.PositiveIntegerField(choices=[(0, 'Amostra'), (0, 'Demonstração'), (0, 'Licenciado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'SUGESTÃO'), (2, 'SOLITAÇÃO'), (3, 'RECLAMAÇÃO'), (4, 'RECLAMAÇÃO ANONIMA')], default=1),
        ),
    ]
