# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170508_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='perennitylicense',
            name='data_ultimo_aviso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perennitylicense',
            name='nao_enviar_aviso',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perennitylicense',
            name='active',
            field=models.NullBooleanField(default=True, verbose_name='Licença Ativa'),
        ),
        migrations.AlterField(
            model_name='perennitylicense',
            name='tipo_license',
            field=models.PositiveIntegerField(choices=[(0, 'Amostra'), (1, 'Demonstração'), (2, 'Licenciado')], default=0, verbose_name='Status'),
        ),
    ]
