# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170518_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePytech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reff', models.PositiveIntegerField(verbose_name='ID Sistech')),
                ('name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apelido')),
                ('comments', models.TextField(blank=True, null=True)),
                ('active', models.NullBooleanField(default=False)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Hospital'), (2, 'Clinica Medica'), (3, 'Graficas'), (4, 'Igrejas'), (5, 'Industrias'), (6, 'Epresas de Seguranças'), (7, 'Outros')], default=1, verbose_name='Ramo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['-created'],
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='GrupoClientePytech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPytech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='DESC')),
                ('sn', models.CharField(max_length=18, verbose_name='SN')),
            ],
        ),
    ]
