# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_clientepytech_grupoclientepytech_produtopytech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtopytech',
            options={'ordering': ['-id'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produtopytech',
            name='ativo',
            field=models.NullBooleanField(default=True),
        ),
    ]
