# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170630_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtopytech',
            options={'ordering': ['-id'], 'verbose_name': 'Pytech Produto ', 'verbose_name_plural': 'Pytech Produtos'},
        ),
        migrations.AddField(
            model_name='produtopytech',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.ClientePytech'),
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='CLIENTES',
        ),
        migrations.AlterModelTable(
            name='grupousuarios',
            table='GRUPO_USUARIOS',
        ),
        migrations.AlterModelTable(
            name='techuser',
            table='USUARIOS',
        ),
    ]
